#!/usr/bin/python
print "Content-Type: text/html\n"
import cgi, cgitb
cgitb.enable()
form = cgi.FieldStorage()

items = 3
imgs = [i for i in range(items)]
imgs[0] = "http://www.cs.indiana.edu/classes/a348-dger/spr2006/new.gif"
imgs[1] = "http://www.cs.indiana.edu/classes/a348-dger/spr2006/due.gif"
imgs[2] = "http://www.cs.indiana.edu/classes/a348-dger/spr2006/classNotes.gif"

if form:
  ac = form.getvalue("action")
  i = int(form.getvalue("index"))
  if ac == "previous":
    if i == 0:
      i = items - 1
    else:
      i-=1
  else:
    if ac=="next":
      if i + 1 == items:
        i = 0
      else:
        i+=1
    else:
      i = 0
else:
  i = 0

print """
<html>
  <head>
  <title>Oredered Picture</title>
  </head>
  <body>
    <table>
      <tr> <td align=center> 
      <img src=%s>
      <tr><td align=center> 
      <form>
        <input type="submit" name="action" value="previous" />
        <input type="submit" name="action" value="next" />
        <input type="hidden" name="index" value=%s />
      </form>
      Picture Index: <br> %s 
      <tr> <td align=center>
      <font size=-1>Note: this program goes through all pictures in order (back and forth). <p> 
      Note also that when the pictures end we start again from the other end. </font> 
    </table> <p>
  </body>
</html>
""" % (imgs[i],i,i)
