#!/usr/bin/python

print "Content-Type: text/html"     # HTML is following
print                               # blank line, end of headers

import cgi

import cgitb
cgitb.enable()

form = cgi.FieldStorage()
print form
